site_name: TiPortfolio Docs
repo_url: https://github.com/TradeInsight-Info/TiPortfolio

theme:
  # name: readthedocs
  name: material
  features:
    - search.highlight
    - search.suggest
    - navigation.footer


plugins:
  - mkdocstrings
  - search
  - offline

extra:
  version:
    provider: mike


nav:
  - Home: index.md
  - Guides and Examples:
    - Debug: debug.md
    - Usage: guides/usage.md
    - Rebalance:
      - guides/fix-tim-rebalance.md
      - guides/market-volatility-rebalance.md
    - Allocation Strategy:

  - Why TiPortfolio:
    - thoughts.md
  

  - API Reference:
    - api/index.md
    - Module 1: api/module1.md
    - Module 2: api/module2.md
  - About: about.md
  - Reference:
    - Researching: papers.md
  - Changelog: https://github.com/TradeInsight-Info/TiPortfolio/releases